name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        framework: ["toga"]
        include:
          - os_name: macOS
            platform: macos-12
            briefcase-data-dir: ~/Library/Caches/org.beeware.briefcase
            pip-cache-dir: ~/Library/Caches/pip
            docker-cache-dir: ~/Library/Containers/com.docker.docker/Data/vms/0/
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3.0.11
        with:
          key: briefcase-${{ matrix.platform }}-${{ matrix.python_version }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install packages
        run: pip install briefcase
      - name: Build iOS App
        run: |
          cd tests/apps/verify-${{ matrix.framework }}
          briefcase create iOS
          briefcase build iOS -d "iPhone SE (2nd generation)"
          briefcase package iOS --adhoc-sign
